### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by ghost** [mtsch/mtsch-vcvrack-plugins#1]
[mtsch-plugins-0.5.1-win.zip](https://github.com/mtsch/mtsch-vcvrack-plugins/files/1611272/mtsch-plugins-0.5.1-win.zip)

**Comment by mtsch** [comment]
Thanks for the quick build!

**Comment by ghost** [comment]
merged your PR ;) its now available throu the plugin manager

**Comment by mtsch** [comment]
Thanks again!
