### ISSUE TITLE
Mac compile error

### ISSUE THREAD

**Issue by Motopomp** [mtsch/mtsch-vcvrack-plugins#2]
i have 1 error on compiling , see screenshot
![capture d ecran 2018-01-08 a 12 05 01](https://user-images.githubusercontent.com/33150728/34668158-5f08b98a-f46c-11e7-82a9-26ce732e1692.png)

**Comment by cfoulc** [comment]
at moto pomp get newer Rack dev, my friend :) 
[mtsch-plugins-0.5.1-mac.zip](https://github.com/mtsch/mtsch-vcvrack-plugins/files/1611304/mtsch-plugins-0.5.1-mac.zip)

**Comment by Motopomp** [comment]
thx a lot………

**Comment by mtsch** [comment]
Thanks for the build!

**Comment by nay-seven** [comment]
mm, no .dylib file in the zip ?

**Comment by cfoulc** [comment]
oups, sorry, missed some thing

**Comment by cfoulc** [comment]
i'm on it

**Comment by mtsch** [comment]
Sorry, looks like I forgot to add plugin.* to the the Makefile.

**Comment by cfoulc** [comment]
better here, sorry again :)
[mtsch-plugins-0.5.1-mac.zip](https://github.com/mtsch/mtsch-vcvrack-plugins/files/1611332/mtsch-plugins-0.5.1-mac.zip)

**Comment by nay-seven** [comment]
no worries ! thanks !

**Comment by cfoulc** [comment]
here is the makefile i used : 
[Makefile.zip](https://github.com/mtsch/mtsch-vcvrack-plugins/files/1611343/Makefile.zip)

**Comment by mtsch** [comment]
This build looks good, thanks!
