### ISSUE TITLE
Error on opening examples

### ISSUE THREAD

**Issue by nay-seven** [mtsch/mtsch-vcvrack-plugins#3]
Hello,
Thanks for your plug-ins, 
I've tried to open the 2 examples files with the fresh Mac release and got this message 

JSON parsing error at <stream> 7:1 '[' or '{' expected near '<'

Mac Yosemite here

**Comment by mtsch** [comment]
Hey, just double-checked and they work fine on my machine and are up to date in the repo.
I'm not sure what the problem could be, since they are just save files from Rack.

**Comment by nay-seven** [comment]
ok, solved, 
at first i download it directly from here, from the example folder ( right click save as) and i've try again with the clone or download feature to download all the source , then extract the examples, it's ok 
_( just need to wait for a mac release for the new ones ;-) )_
