### ISSUE TITLE
error on compile - macos

### ISSUE THREAD

**Issue by JerrySievert** [mtsch/mtsch-vcvrack-plugins#4]
hi, I've run into an error trying to compile v0.5.2 from the releases on macOS:

```
src/Sum.cpp:61:30: error: use of undeclared identifier 'CKSSThree'
        addParam(createParam<CKSSThree>(Vec(X_POSITION + 30, Y_INPUT_POS...
```

is there an easy way around this?

thanks!

**Comment by mtsch** [comment]
Hey, make sure you have the latest version of Rack (0.5.1). Aparrently `CKSSThree` isn't defined in 0.5.0.

**Comment by JerrySievert** [comment]
awesome, thanks! working now.
